!pip install numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [5]:
type(arr), type(np.ndarray)

(numpy.ndarray, type)

In [6]:
arr.shape

(3, 3)

In [7]:
arr.dtype

dtype('int32')

In [8]:
np.int32, np.int64, np.bool, np.float16, np.float32, np.float64, np.object

(numpy.int32,
 numpy.int64,
 bool,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 object)

In [28]:
arr1 = np.array([[0,1,2], [4, 2.3, 6], [7,8,9]])

In [29]:
arr1

array([[0. , 1. , 2. ],
       [4. , 2.3, 6. ],
       [7. , 8. , 9. ]])

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr1[0][0], type(arr1[0][0])

(0.0, numpy.float64)

In [38]:
arr.astype(np.int64)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [39]:
np.int64(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [44]:
arr2 = arr.reshape((1, 9)) #arr.reshape(1, 9)

In [45]:
arr.shape, arr2.shape

((3, 3), (1, 9))

In [47]:
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [48]:
arr3.shape

(4, 3)

In [50]:
arr4 = arr3.reshape(2,2,3)

In [51]:
arr4.shape

(2, 2, 3)

In [52]:
arr4[0][0]

array([1, 2, 3])

In [ ]:
# A => (2, 14) , B => (3, 4, 1, 6, 1)

In [59]:
np.array([   [[[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]]],         [[[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]]],         [[[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]],  [[[1],[2],[3],[4],[5],[6]]]]       ]).shape

(3, 4, 1, 6, 1)

In [71]:
# A => (1,1,1,2,1,2,1,2)

In [73]:
np.array([

    [
        [
            [
                [
                    [
                        [[1,2]],
                        [[3,4]]
                    ]
                ], 
                [
                    [
                        [[5,6]],
                        [[6,7]]
                    ]
                ]
            ]
        ]
    ]    

]).shape

(1, 1, 1, 2, 1, 2, 1, 2)

In [ ]:
# A => (224, 224, 3)

In [76]:
2 * [1,2] # [1,2] + [1,2] <= concatenation

[1, 2, 1, 2]

In [79]:
# __add__

In [78]:
print(2 * np.array([1,2])) 
print(np.array([1,2]) + np.array([1,2])) # <= actual addition

[2 4]
[2 4]


In [80]:
a = np.array([1,2])
b = np.array([3,4])

In [82]:
a / b

array([0.33333333, 0.5       ])

In [85]:
2 / a # => np.array([2,2]) / a

array([2., 1.])

In [86]:
c = np.array([[1, 2, 3], [20,30,40]])

In [87]:
c.shape

(2, 3)

In [94]:
1 + c #=> np.array([[1,1,1],[1,1,1]]) + c

array([[ 2,  3,  4],
       [21, 31, 41]])

In [95]:
d = np.array([[1,2]])

In [96]:
d.shape

(1, 3)

In [98]:
ans = d + c

In [99]:
ans.shape

(2, 3)

In [ ]:
[
    [
        1,2,3
    ],
    [
        4,5,6
    ],
    [
        7,8,9
    ],
    [
        10, 11, 12
    ]
] # 4,3

In [ ]:
[
    [
        [
            1,2,3
        ],
        [
            4,5,6
        ],
    ],
    [
        [
            1,2,3
        ],
        [
            4,5,6
        ]
    ]
] # 2,2,3

In [123]:
x = np.random.randint(0, 10, (2,2,3))
y = np.random.randint(0, 10, (2,3))

In [124]:
x + y

array([[[10, 13, 10],
        [12,  9, 10]],

       [[12, 18, 11],
        [ 7, 16, 13]]])

In [137]:
x = np.random.randint(0, 10, (50, 100, 1, 3))
y = np.random.randint(0, 10, (1, 3))

# x + y

In [140]:
t = np.random.randint(0, 10, (1,78,291,27))

In [141]:
1 * 78 * 291 * 27

612846

In [146]:
612846//2

306423

In [154]:
(612846/2)/4 # => 612846/(4*2)

102141.0

In [158]:
t.reshape(2, 3, -1).shape

(2, 3, 102141)

In [163]:
# np.ones((100,2))
# np.zeros((100,2))

In [184]:
np.linspace(0, 10, endpoint=False, num=10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [182]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [177]:
(0.2 + 0.1) == 0.3

False

In [178]:
10/7

1.4285714285714286

In [169]:
0, 10

1.1

In [186]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [189]:
z = np.arange(0, 10)

In [192]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
z.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [194]:
z.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [198]:
np.random.randint(1,10, size=(3,))

array([3, 8, 8])