In [1]:
import matplotlib.pyplot as plt
import numpy as np

W = (X<sup>T</sup>X)<sup>-1</sup>X<sup>T</sup>Y

In [2]:
X, y = np.load("../Data/LinearRegression/X_data.npy"), np.load("../Data/LinearRegression/Y_data.npy").reshape(-1,1)

In [3]:
X.shape, y.shape

((100, 3), (100, 1))

In [4]:
mat1 = np.ones((3,2))
mat2 = np.ones((3,2))

mat1.T.dot(mat2)

array([[3., 3.],
       [3., 3.]])

In [5]:
# np.stack([mat1, mat2], axis=0).reshape(-1, 2).shape
np.concatenate([mat1, mat2], axis=1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
def fit(X, y):
    X = np.copy(X)
    ones_column = np.ones((len(X), 1))
    # np.stack([ones_column, X], axis=1).reshape(-1, X.shape[1])
    X = np.concatenate([ones_column, X], axis=1)

    W = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
    return W

def predict(X, W):
    X = np.copy(X)
    ones_column = np.ones((len(X), 1))
    X = np.concatenate([ones_column, X], axis=1)
    
    return X.dot(W)

In [7]:
W = fit(X, y)

In [8]:
y_pred = predict(X, W)

In [9]:
(y - y_pred).sum()

-4.689582056016661e-13

In [10]:
1e-2 # 1 x 10^-2

0.01

In [11]:
W

array([[-0.77588426],
       [85.83960823],
       [37.51369037],
       [45.03995795]])